### ISSUE TITLE
Choose one color for standardization

### ISSUE THREAD

**Issue by adarisa** [Syarifah13/LabWeek9#10]
![image](https://user-images.githubusercontent.com/92793541/200232999-7da188c7-e506-42fc-ac1d-a63c20774b99.png)
![image](https://user-images.githubusercontent.com/92793541/200233259-e731d245-97ad-4594-b4b1-325f41cb9ca2.png)

**Comment by IguchiKikue** [comment]
In my opinion, the color purple is more suitable then yellow

**Comment by adarisa** [comment]
Alright, please do change the colour

**Comment by IguchiKikue** [comment]
Noted and will proceed with changes
